# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archive.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yamcs_pb2
import commanding_pb2
import pvalue_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='archive.proto',
  package='archive',
  serialized_pb=_b('\n\rarchive.proto\x12\x07\x61rchive\x1a\x0byamcs.proto\x1a\x10\x63ommanding.proto\x1a\x0cpvalue.proto\"7\n\nColumnData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.yamcs.Value\"A\n\nStreamData\x12\x0e\n\x06stream\x18\x01 \x01(\t\x12#\n\x06\x63olumn\x18\x02 \x03(\x0b\x32\x13.archive.ColumnData\"o\n\tTableData\x12.\n\x06record\x18\x01 \x03(\x0b\x32\x1e.archive.TableData.TableRecord\x1a\x32\n\x0bTableRecord\x12#\n\x06\x63olumn\x18\x01 \x03(\x0b\x32\x13.archive.ColumnData\"(\n\nColumnInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"k\n\tTableInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\tkeyColumn\x18\x02 \x03(\x0b\x32\x13.archive.ColumnInfo\x12(\n\x0bvalueColumn\x18\x03 \x03(\x0b\x32\x13.archive.ColumnInfo\"?\n\nStreamInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x06\x63olumn\x18\x02 \x03(\x0b\x32\x13.archive.ColumnInfoB\x14\n\x12org.yamcs.protobuf')
  ,
  dependencies=[yamcs_pb2.DESCRIPTOR,commanding_pb2.DESCRIPTOR,pvalue_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLUMNDATA = _descriptor.Descriptor(
  name='ColumnData',
  full_name='archive.ColumnData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='archive.ColumnData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='archive.ColumnData.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=126,
)


_STREAMDATA = _descriptor.Descriptor(
  name='StreamData',
  full_name='archive.StreamData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='archive.StreamData.stream', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column', full_name='archive.StreamData.column', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=193,
)


_TABLEDATA_TABLERECORD = _descriptor.Descriptor(
  name='TableRecord',
  full_name='archive.TableData.TableRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='archive.TableData.TableRecord.column', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=306,
)

_TABLEDATA = _descriptor.Descriptor(
  name='TableData',
  full_name='archive.TableData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='archive.TableData.record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TABLEDATA_TABLERECORD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=306,
)


_COLUMNINFO = _descriptor.Descriptor(
  name='ColumnInfo',
  full_name='archive.ColumnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='archive.ColumnInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='archive.ColumnInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=348,
)


_TABLEINFO = _descriptor.Descriptor(
  name='TableInfo',
  full_name='archive.TableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='archive.TableInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyColumn', full_name='archive.TableInfo.keyColumn', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valueColumn', full_name='archive.TableInfo.valueColumn', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=457,
)


_STREAMINFO = _descriptor.Descriptor(
  name='StreamInfo',
  full_name='archive.StreamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='archive.StreamInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column', full_name='archive.StreamInfo.column', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=522,
)

_COLUMNDATA.fields_by_name['value'].message_type = yamcs_pb2._VALUE
_STREAMDATA.fields_by_name['column'].message_type = _COLUMNDATA
_TABLEDATA_TABLERECORD.fields_by_name['column'].message_type = _COLUMNDATA
_TABLEDATA_TABLERECORD.containing_type = _TABLEDATA
_TABLEDATA.fields_by_name['record'].message_type = _TABLEDATA_TABLERECORD
_TABLEINFO.fields_by_name['keyColumn'].message_type = _COLUMNINFO
_TABLEINFO.fields_by_name['valueColumn'].message_type = _COLUMNINFO
_STREAMINFO.fields_by_name['column'].message_type = _COLUMNINFO
DESCRIPTOR.message_types_by_name['ColumnData'] = _COLUMNDATA
DESCRIPTOR.message_types_by_name['StreamData'] = _STREAMDATA
DESCRIPTOR.message_types_by_name['TableData'] = _TABLEDATA
DESCRIPTOR.message_types_by_name['ColumnInfo'] = _COLUMNINFO
DESCRIPTOR.message_types_by_name['TableInfo'] = _TABLEINFO
DESCRIPTOR.message_types_by_name['StreamInfo'] = _STREAMINFO

ColumnData = _reflection.GeneratedProtocolMessageType('ColumnData', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNDATA,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.ColumnData)
  ))
_sym_db.RegisterMessage(ColumnData)

StreamData = _reflection.GeneratedProtocolMessageType('StreamData', (_message.Message,), dict(
  DESCRIPTOR = _STREAMDATA,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.StreamData)
  ))
_sym_db.RegisterMessage(StreamData)

TableData = _reflection.GeneratedProtocolMessageType('TableData', (_message.Message,), dict(

  TableRecord = _reflection.GeneratedProtocolMessageType('TableRecord', (_message.Message,), dict(
    DESCRIPTOR = _TABLEDATA_TABLERECORD,
    __module__ = 'archive_pb2'
    # @@protoc_insertion_point(class_scope:archive.TableData.TableRecord)
    ))
  ,
  DESCRIPTOR = _TABLEDATA,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.TableData)
  ))
_sym_db.RegisterMessage(TableData)
_sym_db.RegisterMessage(TableData.TableRecord)

ColumnInfo = _reflection.GeneratedProtocolMessageType('ColumnInfo', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNINFO,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.ColumnInfo)
  ))
_sym_db.RegisterMessage(ColumnInfo)

TableInfo = _reflection.GeneratedProtocolMessageType('TableInfo', (_message.Message,), dict(
  DESCRIPTOR = _TABLEINFO,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.TableInfo)
  ))
_sym_db.RegisterMessage(TableInfo)

StreamInfo = _reflection.GeneratedProtocolMessageType('StreamInfo', (_message.Message,), dict(
  DESCRIPTOR = _STREAMINFO,
  __module__ = 'archive_pb2'
  # @@protoc_insertion_point(class_scope:archive.StreamInfo)
  ))
_sym_db.RegisterMessage(StreamInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022org.yamcs.protobuf'))
# @@protoc_insertion_point(module_scope)
